---
- name: SonarQube Admin User Setup
  hosts: all
  become: yes
  vars:
    sonarqube_url: "http://localhost:9000"  # Adjust to match your SonarQube URL
    admin_user: "admin"                     # Default SonarQube admin user
    admin_password: "admin"                 # Default admin password (assumed to be default if setting up first user)
    new_admin_username: "new_admin"         # Desired username for the new admin user
    new_admin_password: "new_strong_password" # Desired strong password for new admin user
    new_admin_email: "admin@example.com"    # Email address of new admin

  tasks:
  - name: Change SonarQube admin password using API
    command: |
      curl -u {{ admin_user }}:{{ admin_password }} -X POST "http://localhost:9000/api/users/change_password?login=${{ admin_user }}&previousPassword=newAdminPassword&password=admim"    
    register: password_change_result

  - name: Debug password change result
    debug:
      var: password_change_result
