- name: Use Docker without Sudo
  hosts: all
  become: yes
  
  tasks:
    - name: Create docker group if it doesn't exist
      group:
        name: docker
        state: present

    - name: Add the current user to the docker group
      user:
        name: "ubuntu"
        groups: docker
        append: yes

    - name: Add Jenkins user to the docker group
      user:
        name: jenkins
        groups: docker
        append: yes

    - name: Restart Docker service to apply group changes
      service:
        name: docker
        state: restarted

    - name: Notify user about re-login requirement
      debug:
        msg: "Please log out and log back in for the changes to take effect."