- name: Automated SonarQube Installation and User Creation
  hosts: all
  become: yes

  vars:
    jenkins_username: "admin"
    jenkins_password: "admin"
    jenkins_url: "http://localhost:8080"
    job_name: "my-example-job"
    job_config: |
      <project>
        <description>This is an example job created by Ansible.</description>
        <builders>
          <hudson.tasks.Shell>
            <command>echo "Hello, Jenkins!"</command>
          </hudson.tasks.Shell>
        </builders>
      </project>

  tasks:
    - name: Create cookie jar
      command: mktemp
      register: cookie_jar 

    - name: Generate API token for the user
      shell: |
        full_crumb=$(curl -u "{{ jenkins_username }}:{{ jenkins_password }}" --cookie-jar "{{ cookie_jar.stdout }}" "{{ jenkins_url }}/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,%22:%22,//crumb)")
        only_crumb=$(echo "$full_crumb" | cut -d: -f2)
        curl -X POST -u "{{ jenkins_username }}:{{ jenkins_password }}" "{{ jenkins_url }}/me/descriptorByName/jenkins.security.ApiTokenProperty/generateNewToken" \
          -H "Connection: keep-alive" \
          -H "Accept: application/json, text/javascript, */*; q=0.01" \
          -H "X-Requested-With: XMLHttpRequest" \
          -H "$full_crumb" \
          -H "Content-Type: application/x-www-form-urlencoded" \
          --cookie "{{ cookie_jar.stdout }}" \
          --data-raw 'newTokenName=ansible-token'
      register: api_token_output

    - name: Store only the API token
      set_fact:
        api_token: "{{ api_token_output.stdout | from_json | json_query('data.tokenValue') }}"

    - name: Debug API token
      debug:
        var: api_token

    # - name: Create Jenkins job
    #   community.general.jenkins_job:
    #     name: "{{ job_name }}"
    #     config: "{{ job_config }}"
    #     url: "{{ jenkins_url }}"
    #     user: "{{ jenkins_username }}"
    #     token: "{{ api_token }}"
  
    # - name: Trigger build for Jenkins job
    #   community.general.jenkins_build:
    #     name: "{{ job_name }}"
    #     state: present
    #     url: "{{ jenkins_url }}"
    #     user: "{{ jenkins_username }}"
    #     token: "{{ api_token }}"    

